# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_photo', models.ImageField(upload_to='')),
                ('event_name', models.CharField(max_length=50)),
                ('weekday', models.CharField(choices=[('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location_name', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=250)),
                ('suite', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('zip_code', models.IntegerField(max_length=15)),
                ('room', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('duration', models.CharField(max_length=200)),
                ('event_format', multiselectfield.db.fields.MultiSelectField(choices=[('BB', 'Big Book Study'), ('C', 'Closed meeting for those who disire to stop using cocaine and all other substances. Newcommers welcome.'), ('CL', 'Candle Light'), ('LS', 'Literature Study'), ('M', 'Mend only'), ('NC', 'No children please.'), ('SB', 'Non smoking with break.'), ('W', 'Women only.'), ('HC', 'Wheelchair accessible')], max_length=200)),
                ('accessiblility', models.CharField(max_length=150)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='InternalResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('upload', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.IntegerField(max_length=2)),
                ('meeting_name', models.CharField(max_length=50)),
                ('weekday', models.CharField(choices=[('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location_name', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=250)),
                ('suite', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('zip_code', models.IntegerField(max_length=15)),
                ('room', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('duration', models.CharField(max_length=200)),
                ('meeting_format', multiselectfield.db.fields.MultiSelectField(choices=[('BB', 'Big Book Study'), ('C', 'Closed meeting for those who disire to stop using cocaine and all other substances. Newcommers welcome.'), ('CL', 'Candle Light'), ('LS', 'Literature Study'), ('M', 'Mend only'), ('NC', 'No children please.'), ('SB', 'Non smoking with break.'), ('W', 'Women only.'), ('HC', 'Wheelchair accessible')], max_length=200)),
                ('accessiblility', models.CharField(max_length=150)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
