# Generated by Django 2.0 on 2017-12-20 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca_events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='accessiblility',
            new_name='accessibility',
        ),
    ]
