# Generated by Django 2.0 on 2017-12-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_format',
            field=models.CharField(max_length=30),
        ),
    ]
