# Generated by Django 2.0 on 2017-12-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='events',
            name='accessibility',
            field=models.BooleanField(default=False),
        ),
    ]
