# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_events', '0002_auto_20171218_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='district',
            field=models.IntegerField(),
        ),
    ]
