# Generated by Django 2.0 on 2017-12-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_events', '0002_auto_20171221_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='suite',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='suite',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='servicemeeting',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicemeeting',
            name='suite',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
