# Generated by Django 2.0 on 2017-12-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_events', '0003_auto_20171221_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
