# Generated by Django 2.0 on 2017-12-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_events', '0004_auto_20171221_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
